const GAME_WIDTH = 900;
const GAME_HEIGHT = 500;

const ENEMY_WIDTH = 63;
const ENEMY_HEIGHT = 110;
const MAX_ENEMIES = 4;

const PLAYER_WIDTH = 87;
const PLAYER_HEIGHT = 97;
const PLAYER_Y_POSITION = GAME_HEIGHT - PLAYER_HEIGHT - 10;
